sonar.projectKey=Hachcobovo_devsecops-vampi-pipeline
sonar.organization=hachcobovo

sonar.sources=app.py,config.py,models.py,controllers
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/*.pyc,database/**
sonar.test.inclusions=tests/**
sonar.coverage.exclusions=tests/**

sonar.python.version=3.10
sonar.host.url=https://sonarcloud.io
sonar.python.coverage.reportPaths=coverage.xml