sonar.projectKey=Hachcobovo_devsecops-vampi-pipeline
sonar.organization=hachcobovo

# Chỉ quét các file source của VAmPI
sonar.sources=app.py,config.py,models.py,controllers

# Thư mục chứa tests
sonar.tests=tests
sonar.test.inclusions=tests/**

# Loại khỏi phân tích hoàn toàn
sonar.exclusions=**/__pycache__/**,**/*.pyc,database/**,.github/**

# Loại khỏi yêu cầu coverage
sonar.coverage.exclusions=tests/**,.github/**,*.yml,*.yaml

sonar.python.version=3.10
sonar.host.url=https://sonarcloud.io
sonar.python.coverage.reportPaths=coverage.xml