name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t vampi .

  sast_semgrep:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/security-audit p/python p/flask

  sast_sonarqube:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # Kích hoạt Quality Gate cho Sonar
      - name: SonarQube Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sca_snyk:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk SCA
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=high

  dast_zap:
    needs: [sast_semgrep, sast_sonarqube, sca_snyk]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Chạy ứng dụng bản lỗi (Vulnerable) để quét DAST
        run: docker compose up -d vampi-vulnerable
        
      - name: Chờ ứng dụng khởi động hoàn toàn
        run: sleep 20
        
      - name: Quét lỗ hổng API bằng OWASP ZAP
        run: |
          docker run --network=host -v $(pwd):/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-api-scan.py \
            -t http://localhost:5002/api/v1/openapi.json \
            -f openapi \
            -c zap.conf